### ISSUE TITLE
Uncaught InvalidCharacterError: Failed to execute 'add' on 'DOMTokenList': The token provided ('g...

### ISSUE THREAD

**Issue by Kenara-kwp** [loic-vaumerel/map-plsql-oracle#1]
I opened a .pck file, with both header and body, and pressed Ctrl+Alt+M

**Atom**: 1.58.0 x64
**Electron**: 9.4.4
**OS**: Microsoft Windows 10 Business
**Thrown From**: [map-plsql-oracle](https://github.com/loic-vaumerel/map-plsql-oracle) package 0.3.0

### Stack Trace

Uncaught InvalidCharacterError: Failed to execute 'add' on 'DOMTokenList': The token provided ('get_sscc_max_length
') contains HTML space characters, which are not valid in tokens.

```
At C:\Users\lrp\.atom\packages\map-plsql-oracle\lib\html-builder-tag.js:25

Error: Failed to execute 'add' on 'DOMTokenList': The token provided ('get_sscc_max_length
') contains HTML space characters, which are not valid in tokens.
    at Td._class (/packages/map-plsql-oracle/lib/html-builder-tag.js:25:28)
    at /packages/map-plsql-oracle/lib/map-plsql-oracle-view.js:100:41
    at Array.forEach (<anonymous>)
    at MapPlsqlOracleView.updateResults (/packages/map-plsql-oracle/lib/map-plsql-oracle-view.js:93:14)
    at Object.refreshResults (/packages/map-plsql-oracle/lib/map-plsql-oracle.js:19:29)
    at Object.toggle (/packages/map-plsql-oracle/lib/map-plsql-oracle.js:58:12)
    at HTMLElement.mapPlsqlOracleToggle (/packages/map-plsql-oracle/lib/map-plsql-oracle.js:34:45)
    at CommandRegistry.handleCommandEvent (~/AppData/Local/atom/app-1.58.0/resources/app/static/<embedded>:11:352326)
    at KeymapManager.dispatchCommandEvent (~/AppData/Local/atom/app-1.58.0/resources/app/static/<embedded>:11:1227728)
    at KeymapManager.handleKeyboardEvent (~/AppData/Local/atom/app-1.58.0/resources/app/static/<embedded>:11:1223862)
    at WindowEventHandler.handleDocumentKeyEvent (~/AppData/Local/atom/app-1.58.0/resources/app/static/<embedded>:11:286651)
```

### Commands

```
  2x -1:01.0 map-plsql-oracle:toggle (input.hidden-input)
```

### Non-Core Packages

```
autocomplete-oracle 1.4.4 
build 0.70.0 
build-oracle 1.6.1 
busy-signal 2.0.1 
language-oracle 1.9.0 
map-plsql-oracle 0.3.0 
plsql-linter 2.3.2 
```

**Comment by LaerkeDIKU** [comment]
I opened a .pck file and pressed Ctrl+Alt+m
